using System.Xml.Linq;
using RTPCCurveEditor.Models;

namespace RTPCCurveEditor.Services;

/// <summary>
/// Serialises/deserialises BezierCurve data to/from the Wwise .wproj XML schema.
/// The curve is exported as a series of linear Wwise graph points sampled from
/// the Bézier — Wwise's own curve editor will re-smooth them on import.
/// </summary>
public static class WwiseXmlService
{
    private const int SampleCount = 32; // number of linear segments in the Wwise export

    // ── Export ────────────────────────────────────────────────────────────

    public static string Export(CurveDocument doc)
    {
        var curve = doc.PrimaryCurve;
        var samples = curve.GetPolyline(SampleCount);

        // Map normalised 0..1 → Wwise real-world ranges
        double inMin  = doc.InputMin,  inMax  = doc.InputMax;
        double outMin = doc.OutputMin, outMax = doc.OutputMax;

        var graphPoints = samples.Select((s, i) => new XElement("GraphPoint",
            new XAttribute("x", Lerp(inMin, inMax, s.X).ToString("F4")),
            new XAttribute("y", Lerp(outMin, outMax, s.Y).ToString("F4")),
            new XAttribute("shape", "Linear")
        ));

        var xml = new XElement("WwiseRTPC",
            new XComment($" Generated by RTPC Curve Editor — {DateTime.UtcNow:u} "),
            new XElement("CurveName", doc.WwiseRtpcName.Length > 0 ? doc.WwiseRtpcName : curve.Name),
            new XElement("InputMin",  inMin),
            new XElement("InputMax",  inMax),
            new XElement("OutputMin", outMin),
            new XElement("OutputMax", outMax),
            new XElement("Curve",
                new XAttribute("curveType", "Linear"),
                graphPoints
            )
        );

        return new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            xml
        ).ToString();
    }

    // ── Import ────────────────────────────────────────────────────────────

    /// <summary>
    /// Parse a Wwise XML snippet (single WwiseRTPC element or a full .wproj excerpt)
    /// and return a populated CurveDocument.
    /// </summary>
    public static CurveDocument Import(string xmlText)
    {
        var xdoc = XDocument.Parse(xmlText);
        var root = xdoc.Root ?? throw new InvalidOperationException("Invalid XML.");

        var doc = new CurveDocument
        {
            WwiseRtpcName = root.Element("CurveName")?.Value ?? "Imported Curve",
            InputMin      = ParseDouble(root, "InputMin",  0),
            InputMax      = ParseDouble(root, "InputMax",  100),
            OutputMin     = ParseDouble(root, "OutputMin", 0),
            OutputMax     = ParseDouble(root, "OutputMax", 1),
            Title         = "Imported Wwise RTPC"
        };

        var curve = new BezierCurve { Name = doc.WwiseRtpcName };
        var graphPoints = root.Element("Curve")?.Elements("GraphPoint").ToList()
                          ?? new List<XElement>();

        foreach (var gp in graphPoints)
        {
            double rawX = double.Parse(gp.Attribute("x")?.Value ?? "0");
            double rawY = double.Parse(gp.Attribute("y")?.Value ?? "0");

            // Normalise back to 0..1
            double nx = InverseLerp(doc.InputMin,  doc.InputMax,  rawX);
            double ny = InverseLerp(doc.OutputMin, doc.OutputMax, rawY);
            curve.Points.Add(new CurvePoint(Math.Clamp(nx, 0, 1), Math.Clamp(ny, 0, 1)));
        }

        if (curve.Points.Count == 0)
        {
            curve.Points.Add(new CurvePoint(0, 0));
            curve.Points.Add(new CurvePoint(1, 1));
        }

        doc.Curves.Add(curve);
        return doc;
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private static double Lerp(double a, double b, double t) => a + (b - a) * t;
    private static double InverseLerp(double a, double b, double v) =>
        Math.Abs(b - a) < 1e-10 ? 0 : (v - a) / (b - a);
    private static double ParseDouble(XElement el, string name, double fallback) =>
        double.TryParse(el.Element(name)?.Value, out var v) ? v : fallback;
}
