using System.Globalization;
using System.Xml.Linq;
using RTPCCurveEditor.Models;
using RTPCCurveEditor.Presets;

namespace RTPCCurveEditor.Services;

public static class WwiseXmlService
{
    /// <summary>
    /// Export the given curve (not necessarily doc.PrimaryCurve — pass whichever
    /// curve should actually be exported, e.g. the currently active one) to
    /// Wwise RTPC XML format.
    /// Default mode (bakeSampledPoints = true) samples the curve so the shape
    /// reads correctly as plain point data anywhere, including in Wwise itself.
    /// Every export also embeds a private extension block with the exact
    /// original control points and handles (see BuildExactPointsExtension),
    /// so a file round-tripped back through Import() on this app comes back
    /// exactly as exported — regardless of export mode.
    /// </summary>
    public static string Export(CurveDocument doc, BezierCurve curve, bool bakeSampledPoints = true, int sampleCount = 32)
    {
        double inMin = doc.InputMin, inMax = doc.InputMax;
        double outMin = doc.OutputMin, outMax = doc.OutputMax;

        IEnumerable<XElement> graphPoints;

        if (bakeSampledPoints)
        {
            // High-fidelity baking: Sample exact C++ / Bézier evaluation.
            // Omit redundant shape attributes for clean, lightweight XML.
            //
            // GetPolyline's parameter is steps PER SEGMENT, not a total point
            // budget for the whole curve — passing sampleCount straight through
            // was exporting roughly (segments * sampleCount) points, ballooning
            // fast on any curve with more than two control points. Scale it down
            // so sampleCount means what the caller of Export() would expect: an
            // approximate total point count for the exported curve.
            int segmentCount = Math.Max(1, curve.Points.Count - 1);
            int stepsPerSegment = Math.Max(2, sampleCount / segmentCount);
            var polyline = curve.GetPolyline(stepsPerSegment);
            graphPoints = polyline.Select(pt => new XElement("GraphPoint",
                new XAttribute("x", Lerp(inMin, inMax, pt.X).ToString("F4", CultureInfo.InvariantCulture)),
                new XAttribute("y", Lerp(outMin, outMax, pt.Y).ToString("F4", CultureInfo.InvariantCulture))
            ));
        }
        else
        {
            // Control-point export: Map anchor handles to nearest Wwise segment shape
            var sortedPoints = curve.Points.OrderBy(p => p.X).ToList();
            graphPoints = sortedPoints.Select(pt => new XElement("GraphPoint",
                new XAttribute("x", Lerp(inMin, inMax, pt.X).ToString("F4", CultureInfo.InvariantCulture)),
                new XAttribute("y", Lerp(outMin, outMax, pt.Y).ToString("F4", CultureInfo.InvariantCulture)),
                new XAttribute("shape", GetWwiseShapeName(pt))
            ));
        }

        var xml = new XElement("WwiseRTPC",
            new XComment($" Generated by RTPC Curve Editor — {DateTime.UtcNow:u} "),
            new XComment($" Mode: {(bakeSampledPoints ? $"Sampled Polyline ({sampleCount} points)" : "Control Points")} "),
            new XElement("CurveName", !string.IsNullOrWhiteSpace(doc.WwiseRtpcName) ? doc.WwiseRtpcName : curve.Name),
            new XElement("ColorHex", curve.ColorHex),
            new XElement("MappingContext",
                new XElement("InputParameter",
                    new XAttribute("Min", inMin.ToString(CultureInfo.InvariantCulture)),
                    new XAttribute("Max", inMax.ToString(CultureInfo.InvariantCulture))
                ),
                new XElement("OutputTarget",
                    new XAttribute("Min", outMin.ToString(CultureInfo.InvariantCulture)),
                    new XAttribute("Max", outMax.ToString(CultureInfo.InvariantCulture))
                )
            ),
            new XElement("InputMin", inMin.ToString(CultureInfo.InvariantCulture)),
            new XElement("InputMax", inMax.ToString(CultureInfo.InvariantCulture)),
            new XElement("OutputMin", outMin.ToString(CultureInfo.InvariantCulture)),
            new XElement("OutputMax", outMax.ToString(CultureInfo.InvariantCulture)),
            new XElement("Curve", graphPoints),
            BuildExactPointsExtension(curve)
        );

        return new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            xml
        ).ToString();
    }

    // Wwise's curve editor only understands the fixed set of named segment
    // shapes handled in ApplyShapeHandles below (Linear, Constant, SCurve,
    // ExpX, LogX) — it has no concept of an arbitrary bezier handle. So
    // exporting to <Curve>/<GraphPoint> is a genuinely lossy step for any
    // custom curve whose tangents don't already match one of those shapes,
    // and no amount of reconstruction cleverness on Import() can undo that;
    // Wwise itself couldn't represent the original curve exactly either.
    //
    // This extension block sidesteps that for the one case we actually
    // control: re-opening a file THIS app exported. It stores the exact
    // point/handle values as extra, unrecognized XML that Wwise (and any
    // other well-behaved XML consumer) will simply ignore. Import() checks
    // for it first and restores the curve exactly, byte-for-byte in terms of
    // shape, when present, and only falls back to the lossy GraphPoint/shape
    // reconstruction for files that didn't come from this app (e.g. authored
    // directly in Wwise, or exported by an older version of this tool).
    private static XElement BuildExactPointsExtension(BezierCurve curve)
    {
        var culture = CultureInfo.InvariantCulture;
        return new XElement("RTPCCurveEditorExtension",
            new XAttribute("version", "1"),
            new XComment(" Private extension for exact round-trip fidelity when reopened in RTPC Curve Editor. Safe for other tools, including Wwise, to ignore. "),
            new XElement("ExactPoints",
                curve.Points.OrderBy(p => p.X).Select(p => new XElement("Point",
                    new XAttribute("x", p.X.ToString("F6", culture)),
                    new XAttribute("y", p.Y.ToString("F6", culture)),
                    new XAttribute("lhx", p.LeftHandleX.ToString("F6", culture)),
                    new XAttribute("lhy", p.LeftHandleY.ToString("F6", culture)),
                    new XAttribute("rhx", p.RightHandleX.ToString("F6", culture)),
                    new XAttribute("rhy", p.RightHandleY.ToString("F6", culture))
                ))
            )
        );
    }

    public static CurveDocument Import(string xmlText)
    {
        var xdoc = XDocument.Parse(xmlText);
        var root = xdoc.Root ?? throw new InvalidOperationException("Invalid XML structure: missing root element.");

        var doc = new CurveDocument
        {
            WwiseRtpcName = root.Element("CurveName")?.Value ?? "Imported Curve",
            InputMin = ParseDouble(root, "InputMin", 0),
            InputMax = ParseDouble(root, "InputMax", 100),
            OutputMin = ParseDouble(root, "OutputMin", 0),
            OutputMax = ParseDouble(root, "OutputMax", 1),
            Title = "Imported Wwise RTPC"
        };

        var colorHex = root.Element("ColorHex")?.Value;
        var curve = new BezierCurve
        {
            Name = doc.WwiseRtpcName,
            ColorHex = !string.IsNullOrWhiteSpace(colorHex) ? colorHex : "#7F77DD"
        };
        curve.Points.Clear();

        // Prefer the exact round-trip data this app embeds on export (see
        // BuildExactPointsExtension). Files from real Wwise, or from an
        // older version of this tool, won't have this block, so fall back
        // to reconstructing from <GraphPoint>/shape below.
        var exactPoints = TryReadExactPointsExtension(root);
        if (exactPoints != null)
        {
            curve.Points.AddRange(exactPoints);
        }
        else
        {
            ReconstructFromGraphPoints(curve, root, doc);
        }

        if (curve.Points.Count == 0)
        {
            curve.Points.Add(new CurvePoint(0, 0));
            curve.Points.Add(new CurvePoint(1, 1));
        }

        doc.Curves.Clear();
        doc.Curves.Add(curve);
        return doc;
    }

    private static List<CurvePoint>? TryReadExactPointsExtension(XElement root)
    {
        var pointElements = root.Element("RTPCCurveEditorExtension")?.Element("ExactPoints")?.Elements("Point").ToList();
        if (pointElements == null || pointElements.Count == 0) return null;

        var culture = CultureInfo.InvariantCulture;
        var result = new List<CurvePoint>();

        foreach (var el in pointElements)
        {
            var x = el.Attribute("x")?.Value;
            var y = el.Attribute("y")?.Value;
            var lhx = el.Attribute("lhx")?.Value;
            var lhy = el.Attribute("lhy")?.Value;
            var rhx = el.Attribute("rhx")?.Value;
            var rhy = el.Attribute("rhy")?.Value;

            if (x == null || y == null || lhx == null || lhy == null || rhx == null || rhy == null)
                return null; // Malformed extension block — fall back to GraphPoints entirely rather than a partial reconstruction.

            if (!double.TryParse(x, NumberStyles.Float, culture, out double px) ||
                !double.TryParse(y, NumberStyles.Float, culture, out double py) ||
                !double.TryParse(lhx, NumberStyles.Float, culture, out double plhx) ||
                !double.TryParse(lhy, NumberStyles.Float, culture, out double plhy) ||
                !double.TryParse(rhx, NumberStyles.Float, culture, out double prhx) ||
                !double.TryParse(rhy, NumberStyles.Float, culture, out double prhy))
            {
                return null;
            }

            result.Add(new CurvePoint(Math.Clamp(px, 0.0, 1.0), Math.Clamp(py, 0.0, 1.0))
            {
                LeftHandleX = plhx,
                LeftHandleY = plhy,
                RightHandleX = prhx,
                RightHandleY = prhy
            });
        }

        return result;
    }

    private static void ReconstructFromGraphPoints(BezierCurve curve, XElement root, CurveDocument doc)
    {
        var graphPoints = root.Element("Curve")?.Elements("GraphPoint").ToList()
                          ?? new List<XElement>();

        for (int i = 0; i < graphPoints.Count; i++)
        {
            var gp = graphPoints[i];

            var xAttr = gp.Attribute("x")?.Value;
            var yAttr = gp.Attribute("y")?.Value;

            if (xAttr == null || yAttr == null)
                continue; // Skip malformed graph points missing coordinates

            if (!double.TryParse(xAttr, NumberStyles.Float, CultureInfo.InvariantCulture, out double rawX) ||
                !double.TryParse(yAttr, NumberStyles.Float, CultureInfo.InvariantCulture, out double rawY))
            {
                continue;
            }

            string shape = gp.Attribute("shape")?.Value ?? "Linear";

            double nx = InverseLerp(doc.InputMin, doc.InputMax, rawX);
            double ny = InverseLerp(doc.OutputMin, doc.OutputMax, rawY);

            var pt = new CurvePoint(Math.Clamp(nx, 0.0, 1.0), Math.Clamp(ny, 0.0, 1.0));

            // Determine segment spacing to apply proportional handle lengths
            double prevX = i > 0 ? InverseLerp(doc.InputMin, doc.InputMax,
                double.Parse(graphPoints[i - 1].Attribute("x")!.Value, CultureInfo.InvariantCulture)) : nx;
            double nextX = i < graphPoints.Count - 1 ? InverseLerp(doc.InputMin, doc.InputMax,
                double.Parse(graphPoints[i + 1].Attribute("x")!.Value, CultureInfo.InvariantCulture)) : nx;

            // Also track the neighbors' Y so a "Linear" point's tangent can
            // follow the real slope between them (see ApplyShapeHandles).
            double prevY = i > 0 ? InverseLerp(doc.OutputMin, doc.OutputMax,
                double.Parse(graphPoints[i - 1].Attribute("y")!.Value, CultureInfo.InvariantCulture)) : ny;
            double nextY = i < graphPoints.Count - 1 ? InverseLerp(doc.OutputMin, doc.OutputMax,
                double.Parse(graphPoints[i + 1].Attribute("y")!.Value, CultureInfo.InvariantCulture)) : ny;

            double segmentWidth = Math.Max(0.01, (nextX - prevX) * 0.5);
            double localSlope = Math.Abs(nextX - prevX) > 1e-9 ? (nextY - prevY) / (nextX - prevX) : 0.0;

            // Apply matching handles based on the Wwise shape tag
            ApplyShapeHandles(pt, shape, segmentWidth, localSlope);
            curve.Points.Add(pt);
        }
    }

    private static string GetWwiseShapeName(CurvePoint pt)
    {
        if (Math.Abs(pt.RightHandleY - 0.5) < 0.1)
            return "SCurve";

        if (pt.RightHandleY > 0.3)
            return "Exp3";

        if (pt.RightHandleY < -0.3)
            return "Log3";

        return "Linear";
    }

    private static void ApplyShapeHandles(CurvePoint pt, string shape, double segmentWidth, double localSlope)
    {
        double hX = Math.Min(0.25, segmentWidth * 0.33);

        switch (shape)
        {
            case "SCurve":
                pt.RightHandleX = hX; pt.RightHandleY = 0.5;
                pt.LeftHandleX = -hX; pt.LeftHandleY = -0.5;
                break;

            case "Exp3":
            case "Exp1":
                pt.RightHandleX = hX; pt.RightHandleY = 0.4;
                pt.LeftHandleX = -hX; pt.LeftHandleY = -0.1;
                break;

            case "Log3":
            case "Log1":
                pt.RightHandleX = hX; pt.RightHandleY = -0.4;
                pt.LeftHandleX = -hX; pt.LeftHandleY = 0.1;
                break;

            case "Constant":
                // A genuinely held/step value: the tangent really is flat here.
                pt.RightHandleX = hX; pt.RightHandleY = 0.0;
                pt.LeftHandleX = -hX; pt.LeftHandleY = 0.0;
                break;

            default: // Linear
                // A straight line's tangent follows the actual slope between
                // its neighbors, not a flat/horizontal handle. Forcing it flat
                // here was creating a fake "ease" bend at every single point —
                // most visible on baked/sampled exports, since those never
                // write a shape attribute and so always fall through to this
                // case on import.
                pt.RightHandleX = hX; pt.RightHandleY = localSlope * hX;
                pt.LeftHandleX = -hX; pt.LeftHandleY = -localSlope * hX;
                break;
        }
    }

    private static double Lerp(double a, double b, double t) => a + (b - a) * t;

    private static double InverseLerp(double a, double b, double v) =>
        Math.Abs(b - a) < 1e-10 ? 0 : (v - a) / (b - a);

    private static double ParseDouble(XElement el, string name, double fallback) =>
        double.TryParse(el.Element(name)?.Value, NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : fallback;
}