using System.Globalization;
using System.Xml.Linq;
using RTPCCurveEditor.Models;
using RTPCCurveEditor.Presets;

namespace RTPCCurveEditor.Services;

public static class WwiseXmlService
{
    public static string Export(CurveDocument doc)
    {
        var curve = doc.PrimaryCurve;
        double inMin = doc.InputMin, inMax = doc.InputMax;
        double outMin = doc.OutputMin, outMax = doc.OutputMax;

        var sortedPoints = curve.Points.OrderBy(p => p.X).ToList();

        var graphPoints = sortedPoints.Select(pt => new XElement("GraphPoint",
            new XAttribute("x", Lerp(inMin, inMax, pt.X).ToString("F4", CultureInfo.InvariantCulture)),
            new XAttribute("y", Lerp(outMin, outMax, pt.Y).ToString("F4", CultureInfo.InvariantCulture)),
            new XAttribute("shape", GetWwiseShapeName(pt))
        ));

        var xml = new XElement("WwiseRTPC",
            new XComment($" Generated by RTPC Curve Editor — {DateTime.UtcNow:u} "),
            new XElement("CurveName", doc.WwiseRtpcName.Length > 0 ? doc.WwiseRtpcName : curve.Name),
            new XElement("InputMin", inMin.ToString(CultureInfo.InvariantCulture)),
            new XElement("InputMax", inMax.ToString(CultureInfo.InvariantCulture)),
            new XElement("OutputMin", outMin.ToString(CultureInfo.InvariantCulture)),
            new XElement("OutputMax", outMax.ToString(CultureInfo.InvariantCulture)),
            new XElement("Curve",
                new XAttribute("curveType", "Linear"),
                graphPoints
            )
        );

        return new XDocument(
            new XDeclaration("1.0", "utf-8", null),
            xml
        ).ToString();
    }

    public static CurveDocument Import(string xmlText)
    {
        var xdoc = XDocument.Parse(xmlText);
        var root = xdoc.Root ?? throw new InvalidOperationException("Invalid XML.");

        var doc = new CurveDocument
        {
            WwiseRtpcName = root.Element("CurveName")?.Value ?? "Imported Curve",
            InputMin = ParseDouble(root, "InputMin", 0),
            InputMax = ParseDouble(root, "InputMax", 100),
            OutputMin = ParseDouble(root, "OutputMin", 0),
            OutputMax = ParseDouble(root, "OutputMax", 1),
            Title = "Imported Wwise RTPC"
        };

        var curve = new BezierCurve { Name = doc.WwiseRtpcName };
        var graphPoints = root.Element("Curve")?.Elements("GraphPoint").ToList()
                          ?? new List<XElement>();

        for (int i = 0; i < graphPoints.Count; i++)
        {
            var gp = graphPoints[i];
            double rawX = double.TryParse(gp.Attribute("x")?.Value, NumberStyles.Float, CultureInfo.InvariantCulture, out var xVal) ? xVal : 0;
            double rawY = double.TryParse(gp.Attribute("y")?.Value, NumberStyles.Float, CultureInfo.InvariantCulture, out var yVal) ? yVal : 0;
            string shape = gp.Attribute("shape")?.Value ?? "Linear";

            double nx = InverseLerp(doc.InputMin, doc.InputMax, rawX);
            double ny = InverseLerp(doc.OutputMin, doc.OutputMax, rawY);

            var pt = new CurvePoint(Math.Clamp(nx, 0, 1), Math.Clamp(ny, 0, 1));

            // Apply matching handles based on the Wwise shape tag
            ApplyShapeHandles(pt, shape);
            curve.Points.Add(pt);
        }

        if (curve.Points.Count == 0)
        {
            curve.Points.Add(new CurvePoint(0, 0));
            curve.Points.Add(new CurvePoint(1, 1));
        }

        doc.Curves.Add(curve);
        return doc;
    }

    private static string GetWwiseShapeName(CurvePoint pt)
    {
        // Detect non-linear handles and return equivalent Wwise shape string
        if (Math.Abs(pt.RightHandleY - 0.5) < 0.1) return "SCurve";
        if (pt.RightHandleY > 0.3) return "Exp3";
        if (pt.RightHandleY < -0.3) return "Log3";
        return "Linear";
    }

    private static void ApplyShapeHandles(CurvePoint pt, string shape)
    {
        switch (shape)
        {
            case "SCurve":
                pt.RightHandleX = 0.0; pt.RightHandleY = 0.5;
                pt.LeftHandleX = 0.0; pt.LeftHandleY = -0.5;
                break;
            case "Exp3":
                pt.RightHandleX = 0.05; pt.RightHandleY = 0.45;
                pt.LeftHandleX = -0.45; pt.LeftHandleY = -0.05;
                break;
            case "Log3":
                pt.RightHandleX = 0.45; pt.RightHandleY = 0.05;
                pt.LeftHandleX = -0.05; pt.LeftHandleY = -0.45;
                break;
            default: // Linear
                pt.RightHandleX = 0.05; pt.RightHandleY = 0.0;
                pt.LeftHandleX = -0.05; pt.LeftHandleY = 0.0;
                break;
        }
    }

    private static double Lerp(double a, double b, double t) => a + (b - a) * t;
    private static double InverseLerp(double a, double b, double v) =>
        Math.Abs(b - a) < 1e-10 ? 0 : (v - a) / (b - a);
    private static double ParseDouble(XElement el, string name, double fallback) =>
        double.TryParse(el.Element(name)?.Value, NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : fallback;
}